mvc-app/Controllers/TeachersAdminController.cs
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using mvc_app.ViewModels.Course;
using mvc_app.ViewModels.Teacher;

namespace mvc_app.Controllers;

[Route("teachers/admin")]
public class TeachersAdminController : Controller
{
    private readonly IConfiguration _config;
    private readonly IHttpClientFactory _httpClient;
    private readonly string? _baseUrl;
    private readonly JsonSerializerOptions _options;

    public TeachersAdminController(IConfiguration config, IHttpClientFactory httpClient)
    {
        _config = config;
        _httpClient = httpClient;
        _baseUrl = _config.GetSection("apiSettings:baseUrl").Value;
        _options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        using var client = _httpClient.CreateClient();
        var response = await client.GetAsync($"{_baseUrl}/teachers");

        if (!response.IsSuccessStatusCode) return Content("oops");
        var json = await response.Content.ReadAsStringAsync();
        var teachers = JsonSerializer.Deserialize<IList<TeacherListViewModel>>(json, _options);

        return View("Index", teachers);
    }

    [HttpGet("details/{teacherId}")]
    public async Task<IActionResult> Details(int teacherId)
    {
        using var client = _httpClient.CreateClient();
        var response = await client.GetAsync($"{_baseUrl}/teachers/id/{teacherId}");
        if (!response.IsSuccessStatusCode) return Content("oops");

        var json = await response.Content.ReadAsStringAsync();
        var teacher = JsonSerializer.Deserialize<TeacherListViewModel>(json, _options);

        return View("Details", teacher);
    }
}

mvc-app/Views/TeachersAdmin/Details.cshtml
 @model mvc_app.ViewModels.Teacher.TeacherListViewModel

 @{
    Layout = "_LayoutAdmin";
}


<section class="page-content">
        <div class="page-header">
        <h1 class="page-title">Lärare</h1>
    </div>
    <div class="user-details-container">
        <div class="user-details">
            <div class="go-back">
                <a asp-action="Index" asp-controller="TeachersAdmin">Tillbaka</a>
            </div>
            <h2 class="user-details-header">@Model.FirstName @Model.LastName</h2>
                    <table>
                    <thead>
                <tr class="table-header">
                    <th></th>
                    <th>ID</th>
                    <th>Förnamn</th>
                    <th>Efternamn</th>
                    <th>E-mail</th>
                    <th>Telefonnummer</th>
                    <th>Födelsedatum</th>
                    <th>Adress</th>
                    <th>Postnummer</th>
                    <th>Stad</th>
                    <th>Land</th>
                    <th>Kompetenser</th>
                    <th>Aktuella kurser</th>
                    <th></th>
                </tr>
            </thead>
                        <tr class="table-content">
                        <td><a asp-action="Edit" asp-controller="TeachersAdmin" asp-route-teacherId=@Model.Id>Ändra</a>
                        </td>
                        <td>@Model.Id</td>
                        <td>@Model.FirstName</td>
                        <td>@Model.LastName</td>
                        <td>@Model.Email</td>
                        <td>@Model.Phone</td>
                        <td>@Model.BirthDate</td>
                        <td>@Model.Address</td>
                        <td>@Model.PostalCode</td>
                        <td>@Model.City</td>
                        <td>@Model.Country</td>
                        <td>
                            <ul class="skill-list">
                            @foreach (var skill in Model.Skills){
                            <li class="skill-list-item">@skill.Name</li>
                            }
                            </ul>

                        </td>
                        <td>
                            <ul class="course-list">
                                @foreach (var course in Model.Courses){
                                <li>@course.Title</li>
                                }
                            </ul>
                        </td>
                        <td><a asp-action="Delete" asp-controller="TeachersAdmin"
                            asp-route-teacherId=@Model.Id>Radera</a></td>
                    </tr>
                    </table>
        </div>
    </div>
</section>

mvc-app/Views/TeachersAdmin/Index.cshtml
@model IEnumerable<mvc_app.ViewModels.Teacher.TeacherListViewModel>

@{
    Layout = "_LayoutAdmin";
}

<section class="page-content">
    <div class="page-header">
        <h1 class="page-title">Lärare</h1>
    </div>
    <div>
        <a asp-action="Create" asp-controller="TeachersAdmin">Lägg till lärare</a>
    </div>
    <div class="table-container">
        <table>
            <thead>
                <tr class="table-header">
                    <th></th>
                    <th>ID</th>
                    <th>Förnamn</th>
                    <th>Efternamn</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="table-body">
                @foreach (var teacher in Model)
                {
                    <tr class="table-content">
                        <td><a asp-action="Edit" asp-controller="TeachersAdmin" asp-route-userId=@teacher.Id>Ändra</a>
                        </td>
                        <td>@teacher.Id</td>
                        <td>@teacher.FirstName</td>
                        <td>@teacher.LastName</td>
                        <td><a asp-action="Details" asp-route-teacherId="@teacher.Id" asp-controller="TeachersAdmin">Detaljer</a></td>
                        <td><a asp-action="Delete" asp-controller="TeachersAdmin"
                            asp-route-userId=@teacher.Id>Radera</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</section>