mvc-app/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace mvc_app.Controllers;

[Route("admin")]
public class AdminController : Controller
{
    public IActionResult Index()
    {
        return View("Index");
    }
}

mvc-app/Controllers/CoursesAdminController.cs
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using mvc_app.Models;
using mvc_app.ViewModels.Course;
using mvc_app.ViewModels.Student;
using static System.Net.Mime.MediaTypeNames;

namespace mvc_app.Controllers;


[Route("courses/admin")]
public class CoursesAdminController : Controller
{
    private readonly IHttpClientFactory _httpClient;
    private readonly IConfiguration _config;
    private readonly string? _baseUrl;
    private readonly JsonSerializerOptions _options;

    public CoursesAdminController(IConfiguration config, IHttpClientFactory httpClient)
    {
        _httpClient = httpClient;
        _config = config;
        _baseUrl = _config.GetSection("apiSettings:baseUrl").Value;
        _options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
    }

    public async Task<IActionResult> Index()
    {
        using var client = _httpClient.CreateClient();
        var response = await client.GetAsync($"{_baseUrl}/courses");

        if (!response.IsSuccessStatusCode) return Content("oops");
        var json = await response.Content.ReadAsStringAsync();
        var courses = JsonSerializer.Deserialize<IList<CourseListViewModel>>(json, _options);

        return View("Index", courses);
    }

    [HttpGet("enrolled/{courseId}")]
    public async Task<IActionResult> ListEnrolledStudents(int courseId)
    {
        using var client = _httpClient.CreateClient();
        var response = await client.GetAsync($"{_baseUrl}/courses/enrolled/{courseId}");
        if (!response.IsSuccessStatusCode) return Content("oops");

        var json = await response.Content.ReadAsStringAsync();
        var students = JsonSerializer.Deserialize<IList<StudentListViewModel>>(json, _options);
        return View("EnrolledStudents", students);
    }

    [HttpGet("create")]
    public async Task<IActionResult> Create()
    {
        var teachersList = new List<SelectListItem>();

        using var client = _httpClient.CreateClient();

        var response = await client.GetAsync($"{_baseUrl}/teachers");
        if (!response.IsSuccessStatusCode) return Content("oops");
        var json = await response.Content.ReadAsStringAsync();
        var teachers = JsonSerializer.Deserialize<List<TeacherSettings>>(json, _options);

        foreach (var teacher in teachers)
        {
            teachersList.Add(new SelectListItem { Value = teacher.Id.ToString(), Text = teacher.FirstName + teacher.LastName });
        }

        var course = new CoursePostViewModel();

        course.Teachers = teachersList;

        return View("Create", course);
    }

    [HttpPost("create")]
    public async Task<IActionResult> Create(CoursePostViewModel course)
    {
        if (!ModelState.IsValid) return View("Create", course);

        var model = new
        {
            Title = course.Title,
            CourseNumber = course.CourseNumber,
            WeeksDuration = course.WeeksDuration,
            StartDate = course.StartDate,
            EndDate = course.StartDate.AddDays(course.WeeksDuration * 7),
            TeacherId = course.TeacherId
        };

        using var client = _httpClient.CreateClient();
        var content = new StringContent(JsonSerializer.Serialize(model), Encoding.UTF8, Application.Json); // gör om objektet till json

        var response = await client.PostAsync($"{_baseUrl}/courses", content);

        if (response.IsSuccessStatusCode)
        {
            return RedirectToAction(nameof(Index));
        }
        return Content("Hoppsan Kerstin");
    }

    [HttpGet("addteacher/{courseId}")]
    public async Task<IActionResult> AddTeacher(int courseId)
    {
        var teachersList = new List<SelectListItem>();

        using var client = _httpClient.CreateClient();

        var response = await client.GetAsync($"{_baseUrl}/teachers");
        if (!response.IsSuccessStatusCode) return Content("oops");
        var json = await response.Content.ReadAsStringAsync();
        var teachers = JsonSerializer.Deserialize<List<TeacherSettings>>(json, _options);

        foreach (var teacher in teachers)
        {
            teachersList.Add(new SelectListItem { Value = teacher.Id.ToString(), Text = teacher.FirstName + teacher.LastName });

        }
        var course = new CourseAddTeacherViewModel();
        course.Teachers = teachersList;
        return View("AddTeacher", course);
    }

    [HttpPatch("addteacher/{courseId}")]
    public async Task<IActionResult> AddTeacher(int courseId, CourseAddTeacherViewModel addteacher)
    {
        var model = new
        {
            TeacherId = addteacher.TeacherId
        };
        using var client = _httpClient.CreateClient();
        var content = new StringContent(JsonSerializer.Serialize(model), Encoding.UTF8, Application.Json); // gör om objektet till json
        var response = await client.PatchAsync($"{_baseUrl}/courses/addteacher", content);

        if (response.IsSuccessStatusCode)
        {
            return RedirectToAction(nameof(Index));
        }
        return Content("Hoppsan Kerstin");
    }
}

mvc-app/Controllers/CoursesController.cs
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using mvc_app.ViewModels.Course;

namespace mvc_app.Controllers;

[Route("courses")]
public class CoursesController : Controller
{
    private readonly IConfiguration _config;
    private readonly string? _baseUrl;
    private readonly JsonSerializerOptions _options;
    private readonly IHttpClientFactory _httpClient;
    public CoursesController(IConfiguration config, IHttpClientFactory httpClient)
    {
        _httpClient = httpClient;
        _config = config;
        _baseUrl = _config.GetSection("apiSettings:baseUrl").Value;
        _options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
    }


    public async Task<IActionResult> Index()
    {
        using var client = _httpClient.CreateClient();
        var response = await client.GetAsync($"{_baseUrl}/courses");

        if(!response.IsSuccessStatusCode) return Content("oops");
        var json = await response.Content.ReadAsStringAsync();
        var courses = JsonSerializer.Deserialize<IList<CourseListViewModel>>(json, _options);

        return View("Index", courses);
    }
}

mvc-app/Controllers/StudentsAdminController.cs
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using mvc_app.ViewModels.Student;

namespace mvc_app.Controllers;

[Route("students/admin")]
public class StudentsAdminController : Controller
{
    private readonly IConfiguration _config;
    private readonly string? _baseUrl;
    private readonly JsonSerializerOptions _options;
    private readonly IHttpClientFactory _httpClient;
    public StudentsAdminController(IConfiguration config, IHttpClientFactory httpClient)
    {
        _httpClient = httpClient;
        _config = config;
        _baseUrl = _config.GetSection("apiSettings:baseUrl").Value;
        _options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
    }

    public async Task<IActionResult> Index()
    {
        using var client = _httpClient.CreateClient();
        var response = await client.GetAsync($"{_baseUrl}/students");

        if (!response.IsSuccessStatusCode) return Content("ooopsis");

        var json = await response.Content.ReadAsStringAsync();
        var students = JsonSerializer.Deserialize<IList<StudentListViewModel>>(json, _options);
        return View("Index", students);
    }

    [HttpGet("details/{studentId}")]
    public async Task<IActionResult> Details(int studentId)
    {
        using var client = _httpClient.CreateClient();
        var response = await client.GetAsync($"{_baseUrl}/students/id/{studentId}");
        if (!response.IsSuccessStatusCode) return Content("oops");

        var json = await response.Content.ReadAsStringAsync();
        var student = JsonSerializer.Deserialize<StudentListViewModel>(json, _options);

        return View("Details", student);
    }
}

mvc-app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://kit.fontawesome.com/7fb40d9ca8.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css">
    <title>@ViewBag.PageTitle – WestCoast Education</title>

</head>

<body>
    <main>
        <section>
            <nav class="navbar">
                <a asp-action="Index" asp-controller="Admin">Admin</a>
                <ul>
                    <li><a asp-action="Index" asp-controller="Home">Startsida</a></li>
                    <li><a asp-action="Index" asp-controller="Courses">Våra kurser</a></li>
                    <li><a asp-action="Index" asp-controller="Teachers">Lärare</a></li>
                </ul>
            </nav>
        </section>
        @await Html.PartialAsync("_WeeklyOffer")
        @RenderBody()
    </main>
</body>
</html>

mvc-app/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/site.css">
    <title>Westcoast Education</title>
</head>
<body>
    <header>
        <nav>
            <a asp-action="Index" asp-controller="Home">Tillbaka till startsidan</a>
            <ul>
                <li><a asp-action="Index" asp-controller="Admin">Startsida</a></li>
                <li><a asp-action="Index" asp-controller="TeachersAdmin">Lärare</a></li>
                <li><a asp-action="Index" asp-controller="StudentsAdmin">Studenter</a></li>
                <li><a asp-action="Index" asp-controller="CoursesAdmin">Kurser</a></li>
            </ul>
        </nav>
    </header>
    <main>
        @RenderBody()
    </main>
</body>
</html>

mvc-app/Views/Shared/_WeeklyOffer.cshtml
<div class="alert">
    <div class="alert success">
        <h3>Veckans erbjudande</h3>
        <h4>15% rabatt vid köp av on demand-kurser</h4>
        <hr>
    </div>
</div>